services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./main.py:/app/main.py
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:3000
    command: >
      sh -c "mlflow server --backend-store-uri postgresql+psycopg2://mlflow_user:mlflow_pass@postgres/mlflow_db --host
      0.0.0.0 --port 3000"

volumes:
  pgdata:
