[project]
name = "mlflow-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "mlflow>=3.1.0",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]
